# ==== Settings ====

[Font]
# path = "/home/simon/dotfiles/fonts/.local/share/fonts/arial.ttf"
size = 9.0

[Icons]
entry = ''
entry_icon = true

[Colors]
text = "#ffffff"
text_aux = "#888888"
accent = "#333333"
background = "#1a1a1a"

[Window]
width = 200
height = 200
elem_cnr_rad = 5
row_height = 20

[Misc]
search_hint = "Search..."
timeout = 20

# ==== dev ====

[[App]] # terminal emulator
name = "Alacritty"
icon = ''
path = "alacritty"
group = "dev"

[[App]] # dev environment
name = "Emacs"
icon = ''
path = "emacs"
group = "dev"

# ==== image ====

[[App]] # image editor
name = "Gimp"
icon = ''
path = "gimp"
group = "image"

[[App]] # image preview
name = "Eye of Gnome"
icon = ''
path = "eog"
group = "image"

[[App]] # convert images in ~/autodirs/image-to-comp-webp/
name = "Convert to webp"
icon = '󱧾'
path = "/home/simon/dotfiles/scripts/image-to-webp.sh"
group = "image"

# ==== app ====

[[App]]
name = "VLC"
icon = '󰕼'
path = "vlc"
group = "app"

[[App]]
name = "OBS"
icon = '󰄀'
path = "obs"
group = "app"

[[App]]
name = "Torrents"
icon = ''
path = "/home/simon/dotfiles/scripts/launch-transmission-dark.sh"
group = "app"

# ==== browser ====

[[App]]
name = "Firefox"
icon = ''
path = "firefox"
group = "browser"

# ==== music ====

[[App]] # DAW
name = "Reaper"
icon = '󰗅'
path = "/home/simon/opt/REAPER/reaper"
group = "music"

[[App]] # normalize/downmix audio in ~/autodirs/prepare-stems/
name = "Prepare stems"
icon = ''
path = "/home/simon/dotfiles/scripts/prepare-stems.sh"
group = "music"

# ==== appimage ====

[[App]] # configure keyboard layout
name = "Vial"
icon = ''
path = "/home/simon/AppImages/Vial-v0.7.5.AppImage"
group = "appimage"

# ==== system ====

[[App]] # open pcmanfm
name = "Files"
icon = ''
path = "pcmanfm"
group = "system"

[[App]] # open pavucontrol
name = "Audio"
icon = ''
path = "/home/simon/dotfiles/scripts/launch-pavucontrol-dark.sh"
group = "system"

[[App]] # log out
name = "Logout"
icon = '󰍂'
path = "/home/simon/dotfiles/scripts/logout.sh"
group = "system"

# ==== helper ====

[[App]] # color picker with clipboard
name = "Color picker"
icon = ''
path = "/home/simon/dotfiles/scripts/color-picker.sh"
group = "helper"

[[App]] # delete all files in ~/Downloads/
name = "Clear downloads"
icon = ''
path = "/home/simon/dotfiles/scripts/clear-downloads.sh"
group = "helper"

[[App]] # get a random password in global clipboard
name = "Password"
icon = ''
path = "/home/simon/dotfiles/scripts/get-password.sh"
group = "helper"

[[App]] # set a 30 second timer
name = "Set timer (30 sec)"
icon = ''
path = "/home/simon/dotfiles/scripts/timer-30-sec.sh"
group = "helper"

