# ==== Settings ====

[Font]
# path = "/home/simon/dotfiles/fonts/.local/share/fonts/arial.ttf"
size = 10.0

[Icons]
entry = ''
entry_icon = false

[Colors]
text = "#ffffff"
text_aux = "#888888"
accent = "#333333"
background = "#1a1a1a"

[Window]
width = 200
height = 200
elem_cnr_rad = 5
row_height = 20

[Misc]
search_hint = "Search..."
timeout = 20

# ==== Apps ====

[[App]]
name = "Alacritty"
icon = ''
path = "alacritty"

[[App]]
name = "Logout"
icon = '󰍂'
path = "/home/simon/dotfiles/scripts/logout.sh"

[[App]]
name = "Gimp"
icon = ''
path = "gimp"

[[App]]
name = "VLC"
icon = '󰕼'
path = "vlc"

[[App]]
name = "Emacs"
icon = ''
path = "emacs"

[[App]]
name = "Reaper"
icon = '󰗅'
path = "/home/simon/opt/REAPER/reaper"

[[App]]
name = "OBS"
icon = '󰄀'
path = "obs"

[[App]]
name = "Clear downloads"
icon = ''
path = "/home/simon/dotfiles/scripts/clear-downloads.sh"

[[App]]
name = "Convert to webp"
icon = ''
path = "/home/simon/dotfiles/scripts/image-to-webp.sh"

[[App]]
name = "Torrents"
icon = ''
path = "/home/simon/dotfiles/scripts/launch-transmission-dark.sh"

[[App]]
name = "Password"
icon = ''
path = "/home/simon/dotfiles/scripts/get-password.sh"

[[App]]
name = "Vial"
icon = ''
path = "/home/simon/AppImages/Vial-v0.7.5.AppImage"

[[App]]
name = "Set timer (30 sec)"
icon = ''
path = "/home/simon/dotfiles/scripts/timer-30-sec.sh"

[[App]]
name = "Audio"
icon = ''
path = "/home/simon/dotfiles/scripts/launch-pavucontrol-dark.sh"

[[App]]
name = "Qutebrowser"
icon = '󰖟'
path = "qutebrowser"

[[App]]
name = "Firefox"
icon = ''
path = "firefox"

[[App]]
name = "Normalize/downmix audio"
icon = ''
path = "/home/simon/dotfiles/scripts/normalize-and-downmix-audio.sh"

[[App]]
name = "Files"
icon = ''
path = "pcmanfm"
